# Build a simple HelloWorld RISCV-64 C executable
cc_binary(
    name = "helloworld",
    srcs = ["helloworld.c"],
)

# Build a simple HelloWorld RISCV-64 C++ executable
cc_binary(
    name = "helloworld++",
    srcs = ["helloworld.cc"],
)
